# Generated by Django 4.2.26 on 2025-12-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mention_percentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_amount', models.FloatField(verbose_name='总品牌提及百分比')),
                ('r_brand_amount', models.FloatField(verbose_name='推荐类品牌提及百分比')),
                ('nr_brand_amount', models.FloatField(verbose_name='非推荐类品牌提及百分比')),
                ('link_amount', models.FloatField(verbose_name='总链接提及百分比')),
                ('r_link_amount', models.FloatField(verbose_name='推荐类链接提及百分比')),
                ('nr_link_amount', models.FloatField(verbose_name='非推荐类链接提及百分比')),
                ('brand_name', models.CharField(max_length=100, verbose_name='品牌名称')),
                ('keyword_name', models.CharField(max_length=100, verbose_name='关键约束词名称')),
                ('field_name', models.CharField(max_length=100, verbose_name='行业名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '提及百分比',
                'verbose_name_plural': '提及百分比',
            },
        ),
    ]
