# Generated by Django 4.2.26 on 2026-01-25 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0003_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=255, verbose_name='关键词')),
                ('question_id', models.CharField(db_index=True, max_length=100, verbose_name='问题ID')),
                ('question_text', models.TextField(verbose_name='问题内容')),
                ('answer_text', models.TextField(verbose_name='AI回答')),
                ('answer_date', models.DateField(db_index=True, verbose_name='回答日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'AI回答缓存',
                'verbose_name_plural': 'AI回答缓存',
            },
        ),
        migrations.CreateModel(
            name='AILink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_url', models.TextField(verbose_name='链接URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'AI回答链接',
                'verbose_name_plural': 'AI回答链接',
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=255, verbose_name='关键词')),
                ('cluster_id', models.IntegerField(db_index=True, verbose_name='聚类ID')),
                ('main_intent', models.TextField(verbose_name='聚类意图')),
                ('generated_question', models.TextField(verbose_name='生成的问题')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '问题库缓存',
                'verbose_name_plural': '问题库缓存',
            },
        ),
        migrations.CreateModel(
            name='QuestionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=255, verbose_name='关键词')),
                ('question_id', models.CharField(db_index=True, max_length=100, verbose_name='问题ID')),
                ('score', models.IntegerField(db_index=True, verbose_name='评分(0-4)')),
                ('answer_date', models.DateField(db_index=True, verbose_name='评分日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '问题评分缓存',
                'verbose_name_plural': '问题评分缓存',
            },
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(db_index=True, max_length=50, verbose_name='任务类型')),
                ('status', models.CharField(db_index=True, max_length=20, verbose_name='状态')),
                ('retry_count', models.IntegerField(default=0, verbose_name='重试次数')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(db_index=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='执行时长(秒)')),
            ],
            options={
                'verbose_name': '任务执行日志',
                'verbose_name_plural': '任务执行日志',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ZhihuQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=255, verbose_name='关键词')),
                ('question_id', models.IntegerField(db_index=True, verbose_name='问题序号')),
                ('question_text', models.TextField(verbose_name='问题内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '知乎问题缓存',
                'verbose_name_plural': '知乎问题缓存',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='current_stage',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='当前阶段'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_cached',
            field=models.BooleanField(default=False, verbose_name='是否使用缓存'),
        ),
        migrations.AddField(
            model_name='order',
            name='last_error',
            field=models.TextField(blank=True, null=True, verbose_name='最后错误'),
        ),
        migrations.AddField(
            model_name='order',
            name='progress_percentage',
            field=models.IntegerField(default=0, verbose_name='进度百分比'),
        ),
        migrations.AddField(
            model_name='order',
            name='retry_count',
            field=models.IntegerField(default=0, verbose_name='重试次数'),
        ),
        migrations.AddIndex(
            model_name='mention_percentage',
            index=models.Index(fields=['brand_name', 'keyword_name'], name='mvp_mention_brand_n_bcbeb5_idx'),
        ),
        migrations.AddIndex(
            model_name='mention_percentage',
            index=models.Index(fields=['created_at'], name='mvp_mention_created_697067_idx'),
        ),
        migrations.AddIndex(
            model_name='mention_percentage',
            index=models.Index(fields=['field_name'], name='mvp_mention_field_n_7fe424_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='mvp_notific_user_id_7b193b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='mvp_notific_created_137415_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='mvp_order_user_id_6c8cac_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='mvp_order_status_e00319_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['keyword'], name='mvp_order_keyword_e4fe76_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['brand'], name='mvp_order_brand_8d8662_idx'),
        ),
        migrations.AddIndex(
            model_name='zhihuquestion',
            index=models.Index(fields=['keyword', 'created_at'], name='mvp_zhihuqu_keyword_2c4dde_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='zhihuquestion',
            unique_together={('keyword', 'question_id')},
        ),
        migrations.AddField(
            model_name='tasklog',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mvp.order', verbose_name='订单'),
        ),
        migrations.AddIndex(
            model_name='questionscore',
            index=models.Index(fields=['keyword', 'question_id'], name='mvp_questio_keyword_77b112_idx'),
        ),
        migrations.AddIndex(
            model_name='questionscore',
            index=models.Index(fields=['answer_date'], name='mvp_questio_answer__060193_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questionscore',
            unique_together={('keyword', 'question_id', 'answer_date')},
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['keyword', 'cluster_id'], name='mvp_questio_keyword_07a3f1_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['created_at'], name='mvp_questio_created_761e15_idx'),
        ),
        migrations.AddField(
            model_name='ailink',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='mvp.aianswer', verbose_name='关联回答'),
        ),
        migrations.AddIndex(
            model_name='aianswer',
            index=models.Index(fields=['keyword', 'question_id'], name='mvp_aianswe_keyword_e33e36_idx'),
        ),
        migrations.AddIndex(
            model_name='aianswer',
            index=models.Index(fields=['answer_date'], name='mvp_aianswe_answer__8e640a_idx'),
        ),
        migrations.AddIndex(
            model_name='tasklog',
            index=models.Index(fields=['order', 'status'], name='mvp_tasklog_order_i_1ee800_idx'),
        ),
        migrations.AddIndex(
            model_name='tasklog',
            index=models.Index(fields=['task_type', 'status'], name='mvp_tasklog_task_ty_82cab4_idx'),
        ),
        migrations.AddIndex(
            model_name='tasklog',
            index=models.Index(fields=['started_at'], name='mvp_tasklog_started_8140a9_idx'),
        ),
        migrations.AddIndex(
            model_name='ailink',
            index=models.Index(fields=['answer'], name='mvp_ailink_answer__4b233a_idx'),
        ),
    ]
